package Impacto::Model::DB::Finance;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(schema_class => 'Impacto::Schema::Finance');

=head1 NAME

Impacto::Model::DB::Finance - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Impacto>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Impacto::Schema::Finance>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.53

=head1 AUTHOR

André Walker

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
